### ISSUE TITLE
[ios] can I use ios sdk without access token?

### ISSUE THREAD

**Issue by adriantabirta** [maptiler/maplibre-gl-native#2]

**Comment by petr-pokorny-1** [comment]
Here is an [example](https://github.com/maptiler/mobile-code-samples/blob/main/samples/ios-swiftui/TUTORIAL.md) how to use the SDK.

In the example shows how to create simple ios app and how to load the style and vector tiles.

```swift
    // Build the style url
    let styleURL = URL(string: "https://api.maptiler.com/maps/streets/style.json?key=\(mapTilerKey)")
```

The token here is required because style and vector tiles are loaded from MapTiler cloud, but if you have public source or your own server you dont any token.

**Comment by adriantabirta** [comment]
1. What about routing?

2. MapTiler also is not free, is there any examples how to host own tiles server? (Is this even real?)

Tăbîrţă Adrian
iOS, JAVA and GO developer 
+373 60 425424

**Comment by adriantabirta** [comment]
@petr-pokorny-1 could you please help me to setup a self hosted tile server for testing proposes?

**Comment by petr-pokorny-1** [comment]
@adriantabirta you can try to use [TileServerGL](https://github.com/maptiler/tileserver-gl) (written in node). If you want to generate your own vector tiles you might want to check [OpenmapTiles](https://github.com/openmaptiles/openmaptiles).

There is many other options indeed.
